### ISSUE TITLE
想请问如何在Proteus上进行仿真

### ISSUE THREAD

**Issue by laikee99** [392625227/C51-NN-network#1]
您好，
HC系列在Proteus中应该选择什么device呢？
AT89C51似乎不能正常工作！
感谢！

**Comment by 392625227** [comment]
Hi,
这个项目是硬件无关的，只要是支持C语言，应该都可以运行，只需要改写一下这个函数，void Uart_SendByte(unsigned char buf)，为了printf()函数能显示结果。
我使用的www.holychip.cn 的HC系列51MCU硬件验证过。

**Comment by laikee99** [comment]
> Hi,
> 这个项目是硬件无关的，只要是支持C语言，应该都可以运行，只需要改写一下这个函数，void Uart_SendByte(unsigned char buf)，为了printf()函数能显示结果。
> 我使用的www.holychip.cn 的HC系列51MCU硬件验证过。

感谢您的回复！
是的，我使用串口通信仿真成功运行！
